### ISSUE TITLE
When trying to train, get this error message:

### ISSUE THREAD

**Issue by ghost** [claabs/markov-discord#12]
```
(node:10620) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'id' of undefined
    at fetchMessages (C:\markov-discord\index.ts:241:38)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:10620) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

Windows 10 Powershell in Admin mode. Latest markov-discord, latest Node.js with build tools . Had to `npm install -g typescript` to get `npm run build` to work.

**Comment by ghost** [comment]
The next time I try to run it:

```
> markbot@0.7.2 start C:\markov-discord
> node dist/index.js

Markbot by Charlie Laabs
Regenerating Markov corpus...

C:\markov-discord\node_modules\markov-strings\dist\index.js:28
        else if (!data[0].hasOwnProperty('string')) {
                          ^
TypeError: Cannot read property 'hasOwnProperty' of undefined
    at new Markov (C:\markov-discord\node_modules\markov-strings\dist\index.js:28:27)
    at regenMarkov (C:\markov-discord\index.ts:113:18)
    at Client.<anonymous> (C:\markov-discord\index.ts:306:3)
    at Client.emit (events.js:326:22)
    at WebSocketConnection.triggerReady (C:\markov-discord\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:125:17)
    at WebSocketConnection.checkIfReady (C:\markov-discord\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:141:61)
    at GuildCreateHandler.handle (C:\markov-discord\node_modules\discord.js\src\client\websocket\packets\handlers\GuildCreate.js:13:31)
    at WebSocketPacketManager.handle (C:\markov-discord\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:105:65)
    at WebSocketConnection.onPacket (C:\markov-discord\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (C:\markov-discord\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:296:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! markbot@0.7.2 start: `node dist/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the markbot@0.7.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\x\AppData\Roaming\npm-cache\_logs\2020-10-10T15_19_39_994Z-debug.log
```
Then it exits

**Comment by claabs** [comment]
I think this may occur when the number of messages in the channel is a multiple of 100? In https://github.com/claabs/markov-discord/commit/eaedaad5ff1cc039942ce6433fb43423a33e3b92, I put some extra checks in to prevent the first error, which I think should prevent the second error. You may need to delete your `markov.json` and `markovDB.json` to get it started again.

I also updated the docs, since I had `--production` left in on the `npm install`s from before I updated it to TS. If you omit `--production`, you should be able to build without global Typescript installed.

**Comment by ghost** [comment]
Thanks for replying so quickly :) I initially tried deleting markov.json and markovDB.json and the bot would run again, but came up with that initial error from my first message again. 

I deleted the whole thing and started again, with the new instructions in the docs. Now ```!mark train``` brought the following error:
```
(node:12168) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'hasOwnProperty' of undefined
    at new Markov (C:\markov-discord\node_modules\markov-strings\dist\index.js:28:27)
    at regenMarkov (C:\markov-discord\index.ts:113:18)
    at fetchMessages (C:\markov-discord\index.ts:249:3)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:12168) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:12168) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Your installer installed Python 2.7 and I also had 3.7 for MusicBot. I tried uninstalling 3.7 and low and behold, the above error stopped. However in different channels with thousands of messages, it always says
```
Training...
Trained from 0 past human authored messages.
```

Then ```!mark``` causes the following error

```Responding...
Error: Failed to build a sentence after 1000 tries
    at Markov.generate (C:\markov-discord\node_modules\markov-strings\dist\index.js:166:15)
    at generateResponse (C:\markov-discord\index.ts:276:31)
    at Client.<anonymous> (C:\markov-discord\index.ts:366:7)
    at Client.emit (events.js:314:20)
    at MessageCreateHandler.handle (C:\markov-discord\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\markov-discord\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:105:65)
    at WebSocketConnection.onPacket (C:\markov-discord\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (C:\markov-discord\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:296:17)
    at WebSocket.onMessage (C:\markov-discord\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (events.js:314:20)```

**Comment by claabs** [comment]
That's strange. Maybe that API function requires 'Read Message History' permissions?
![image](https://user-images.githubusercontent.com/6274312/95662659-3ad5e780-0afe-11eb-832a-4c29a58ed463.png)
