### ISSUE TITLE
Bot always crashes at midnight

### ISSUE THREAD

**Issue by googleooer** [claabs/markov-discord#2]
I cannot provide a log right now, but it always crashes at midnight while trying to execute the node-schedule part of the code

**Comment by claabs** [comment]
I'll check the log of my running instance. I'm running it inside PM2, so I might not have noticed it crashing on the scheduled function.

**Comment by claabs** [comment]
Yep, I'm seeing it too:
`TypeError: Cannot read property 'execute' of undefined
at Job.invoke (/usr/src/markbot/node_modules/node-schedule/lib/schedule.js:175:14)
at /usr/src/markbot/node_modules/node-schedule/lib/schedule.js:552:11
at Timeout._onTimeout (/usr/src/markbot/node_modules/node-schedule/lib/schedule.js:510:7)
at listOnTimeout (timers.js:327:15)
at processTimers (timers.js:271:5)`
