### ISSUE TITLE
Bot unable to train from existing messages

### ISSUE THREAD

**Issue by NovaPhoenix** [claabs/markov-discord#21]
After updating to the latest commit (updating dependencies and all) the bot is now unable to train from existing channels using the `!mark train` command. It responds to every other command but will not log anything in the console after `!mark train` is issued. Since the corpus isn't large enough to create new messages, I get this error after running `!mark`.

```
Listening...
Responding...
Error: Corpus is empty. There is either no data, or the data is not sufficient to create markov chains.
    at Markov.generate (/home/flatline/builds/markov-discord/node_modules/markov-strings/dist/index.js:145:19)
    at generateResponse (/home/flatline/builds/markov-discord/index.ts:281:31)
    at Client.<anonymous> (/home/flatline/builds/markov-discord/index.ts:386:7)
    at Client.emit (events.js:400:28)
    at MessageCreateAction.handle (/home/flatline/builds/markov-discord/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports (/home/flatline/builds/markov-discord/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/flatline/builds/markov-discord/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/home/flatline/builds/markov-discord/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/home/flatline/builds/markov-discord/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/home/flatline/builds/markov-discord/node_modules/ws/lib/event-target.js:132:16)
Listening...
```

**Comment by claabs** [comment]
Hmm, my instance running on the Docker image seems to train fine. 

Maybe try installing the dependencies with `npm ci` rather than `npm install`. `npm install` could be resolving newer dependencies that break something.

**Comment by NovaPhoenix** [comment]
I've tried that, did not seem to fix it. I'll tey reinstalling from scratch a little later.

**Comment by claabs** [comment]
[Version 2.0](https://github.com/claabs/markov-discord/releases/tag/v2.0.0) pretty much re-wrote everything, so closing this issue as it's irrelevant now.
