### ISSUE TITLE
unknown channel error

### ISSUE THREAD

**Issue by JosephLaptop** [claabs/markov-discord#25]
when i do /listen list it throws this error

2022-01-22 02:18:58.849 +0000] INFO: Recieved slash command
    command: "listen"

/usr/app/node_modules/discord.js/src/rest/RequestHandler.js:350
      throw new DiscordAPIError(data, res.status, request);
            ^
DiscordAPIError: Unknown Channel
    at RequestHandler.execute (/usr/app/node_modules/discord.js/src/rest/RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at RequestHandler.push (/usr/app/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
    at GuildChannelManager.fetch (/usr/app/node_modules/discord.js/src/managers/GuildChannelManager.js:195:20)
    at async Promise.all (index 0)
    at getValidChannels (/usr/app/src/index.ts:102:5)
    at listValidChannels (/usr/app/src/index.ts:518:20)
    at Client.<anonymous> (/usr/app/src/index.ts:758:23)

**Comment by JosephLaptop** [comment]
i have only 2 channels added to /listen on

**Comment by claabs** [comment]
I added some extra logging around the location of the error to try to figure out what's going on.

If you can update, and temporarily set `"logLevel": "trace"` in the config file, let me know what the logs show after that.

**Comment by JosephLaptop** [comment]
Man I'm sorry i forgot to change the channel perms after i fixed the channel perms it seems it fixed itself

**Comment by claabs** [comment]
K no worries. 👍
