### ISSUE TITLE
No permissions to create a config file

### ISSUE THREAD

**Issue by bluemozilla** [claabs/markov-discord#55]
I'm new in this scenario with docker, but reading my logs, i can understand why he doesn't create the config file, see:

2023-12-29 01:47:31 Error: Invalid config
2023-12-29 01:47:31     at Object.<anonymous> (/usr/app/src/config/setup.ts:72:9)
2023-12-29 01:47:31     at Module._compile (node:internal/modules/cjs/loader:1155:14)
2023-12-29 01:47:31     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
2023-12-29 01:47:31     at Module.load (node:internal/modules/cjs/loader:1033:32)
2023-12-29 01:47:31     at Function.Module._load (node:internal/modules/cjs/loader:868:12)
2023-12-29 01:47:31     at Module.require (node:internal/modules/cjs/loader:1057:19)
2023-12-29 01:47:31     at require (node:internal/modules/cjs/helpers:103:18)
2023-12-29 01:47:31     at Object.<anonymous> (/usr/app/src/config/index.ts:2:1)
2023-12-29 01:47:31     at Module._compile (node:internal/modules/cjs/loader:1155:14)
2023-12-29 01:47:31     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
2023-12-29 01:48:43 Error: Invalid config
2023-12-29 01:48:43     at Object.<anonymous> (/usr/app/src/config/setup.ts:72:9)
2023-12-29 01:48:43     at Module._compile (node:internal/modules/cjs/loader:1155:14)
2023-12-29 01:48:43     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
2023-12-29 01:48:43     at Module.load (node:internal/modules/cjs/loader:1033:32)
2023-12-29 01:48:43     at Function.Module._load (node:internal/modules/cjs/loader:868:12)
2023-12-29 01:48:43     at Module.require (node:internal/modules/cjs/loader:1057:19)
2023-12-29 01:48:43     at require (node:internal/modules/cjs/helpers:103:18)
2023-12-29 01:48:43     at Object.<anonymous> (/usr/app/src/config/index.ts:2:1)
2023-12-29 01:48:43     at Module._compile (node:internal/modules/cjs/loader:1155:14)
2023-12-29 01:48:43     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
2023-12-29 01:47:31 [2023-12-29 04:47:31.525 +0000] WARN: No config file detected
2023-12-29 01:47:31 [2023-12-29 04:47:31.525 +0000] INFO: Creating new config file
2023-12-29 01:47:31     newConfigPath: "/usr/app/config/config.json"
2023-12-29 01:47:31 [2023-12-29 04:47:31.528 +0000] INFO: Not allowed to create new config. Continuing...
2023-12-29 01:47:31     err: {
2023-12-29 01:47:31       "type": "Error",
2023-12-29 01:47:31       "message": "EACCES: permission denied, open '/usr/app/config/config.json'",
2023-12-29 01:47:31       "stack":
2023-12-29 01:47:31           Error: EACCES: permission denied, open '/usr/app/config/config.json'
2023-12-29 01:47:31               at Object.openSync (node:fs:590:3)
2023-12-29 01:47:31               at Object.writeFileSync (node:fs:2202:35)
2023-12-29 01:47:31               at Object.writeFileSync (/usr/app/node_modules/jsonfile/index.js:78:13)
2023-12-29 01:47:31               at Object.<anonymous> (/usr/app/src/config/setup.ts:54:8)
2023-12-29 01:47:31               at Module._compile (node:internal/modules/cjs/loader:1155:14)
2023-12-29 01:47:31               at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
2023-12-29 01:47:31               at Module.load (node:internal/modules/cjs/loader:1033:32)
2023-12-29 01:47:31               at Function.Module._load (node:internal/modules/cjs/loader:868:12)
2023-12-29 01:47:31               at Module.require (node:internal/modules/cjs/loader:1057:19)
2023-12-29 01:47:31               at require (node:internal/modules/cjs/helpers:103:18)
2023-12-29 01:47:31       "errno": -13,
2023-12-29 01:47:31       "syscall": "open",
2023-12-29 01:47:31       "code": "EACCES",
2023-12-29 01:47:31       "path": "/usr/app/config/config.json"
2023-12-29 01:47:31     }
2023-12-29 01:47:31 [2023-12-29 04:47:31.543 +0000] ERROR: Validation error(s)
2023-12-29 01:47:31     errors: [
2023-12-29 01:47:31       {
2023-12-29 01:47:31         "value": "",
2023-12-29 01:47:31         "property": "token",
2023-12-29 01:47:31         "children": [],
2023-12-29 01:47:31         "constraints": {
2023-12-29 01:47:31           "isNotEmpty": "token should not be empty"
2023-12-29 01:47:31         }
2023-12-29 01:47:31       }
2023-12-29 01:47:31     ]
2023-12-29 01:48:43 [2023-12-29 04:48:43.128 +0000] WARN: No config file detected
2023-12-29 01:48:43 [2023-12-29 04:48:43.129 +0000] INFO: Creating new config file
2023-12-29 01:48:43     newConfigPath: "/usr/app/config/config.json"
2023-12-29 01:48:43 [2023-12-29 04:48:43.134 +0000] INFO: Not allowed to create new config. Continuing...
2023-12-29 01:48:43     err: {
2023-12-29 01:48:43       "type": "Error",
2023-12-29 01:48:43       "message": "EACCES: permission denied, open '/usr/app/config/config.json'",
2023-12-29 01:48:43       "stack":
2023-12-29 01:48:43           Error: EACCES: permission denied, open '/usr/app/config/config.json'
2023-12-29 01:48:43               at Object.openSync (node:fs:590:3)

It can't create the config file and I can't run to troubleshoot because it stops when the error occurs. Please, I need help to troubleshoot this

**Comment by claabs** [comment]
File permissions are complicated. Try just manually creating the config file yourself.
