### ISSUE TITLE
Docker Error: Not allowed to create new config.

### ISSUE THREAD

**Issue by ghost** [claabs/markov-discord#62]
2024-04-17 15:05:07 [2024-04-17 20:05:07.558 +0000] WARN: No config file detected
2024-04-17 15:05:07 [2024-04-17 20:05:07.558 +0000] INFO: Creating new config file
2024-04-17 15:05:07     newConfigPath: "/usr/app/config/config.json"
2024-04-17 15:05:07 [2024-04-17 20:05:07.560 +0000] INFO: Not allowed to create new config. Continuing...
2024-04-17 15:05:07     err: {
2024-04-17 15:05:07       "type": "Error",
2024-04-17 15:05:07       "message": "EACCES: permission denied, open '/usr/app/config/config.json'",
2024-04-17 15:05:07       "stack":
2024-04-17 15:05:07           Error: EACCES: permission denied, open '/usr/app/config/config.json'
2024-04-17 15:05:07               at Object.openSync (node:fs:590:3)
2024-04-17 15:05:07               at Object.writeFileSync (node:fs:2202:35)
2024-04-17 15:05:07               at Object.writeFileSync (/usr/app/node_modules/jsonfile/index.js:78:13)
2024-04-17 15:05:07               at Object.<anonymous> (/usr/app/src/config/setup.ts:54:8)
2024-04-17 15:05:07               at Module._compile (node:internal/modules/cjs/loader:1155:14)
2024-04-17 15:05:07               at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
2024-04-17 15:05:07               at Module.load (node:internal/modules/cjs/loader:1033:32)
2024-04-17 15:05:07               at Function.Module._load (node:internal/modules/cjs/loader:868:12)
2024-04-17 15:05:07               at Module.require (node:internal/modules/cjs/loader:1057:19)
2024-04-17 15:05:07               at require (node:internal/modules/cjs/helpers:103:18)
2024-04-17 15:05:07       "errno": -13,
2024-04-17 15:05:07       "syscall": "open",
2024-04-17 15:05:07       "code": "EACCES",
2024-04-17 15:05:07       "path": "/usr/app/config/config.json"
2024-04-17 15:05:07     }
2024-04-17 15:05:07 [2024-04-17 20:05:07.568 +0000] ERROR: Validation error(s)
2024-04-17 15:05:07     errors: [
2024-04-17 15:05:07       {
2024-04-17 15:05:07         "value": "",
2024-04-17 15:05:07         "property": "token",
2024-04-17 15:05:07         "children": [],
2024-04-17 15:05:07         "constraints": {
2024-04-17 15:05:07           "isNotEmpty": "token should not be empty"
2024-04-17 15:05:07         }
2024-04-17 15:05:07       }
2024-04-17 15:05:07     ]

I can add a config file (maybe that'll fix the problem), but I don't know where "usr/app/config" should be.

**Comment by Nostalgiac** [comment]
I "fixed" this just by opening up the permissions on the mount point of the folder, then running the docker.

eg. chmod 777 -R /my/host/dir

This is definitely not the ideal or secure permission, but enough to get it working to test :)
